sudo: required
language: java
jdk:
 - oraclejdk8
services:
  - docker
script:
- sudo apt-get install -y sshpass
- ./mvnw clean install -Dmaven.test.skip=true
- echo '
     TOKEN=$TOKEN
     DB_URL=$DB_URL
     DB_USERNAME=$DB_USER
     DB_PASSWORD=$DB_PASS' > envfile.env
- sshpass -p $PASSWORD scp -o StrictHostKeyChecking=no envfile.env $USERNAME@$HOST:$ENVPATH
- sudo docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- sudo docker build . -t $DOCKER_USERNAME/$POLITICAABERTA:1.2.$TRAVIS_BUILD_NUMBER
- sudo docker push $DOCKER_USERNAME/$POLITICAABERTA:1.2.$TRAVIS_BUILD_NUMBER
- sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "
     sudo docker pull $DOCKER_USERNAME/$POLITICAABERTA:1.2.$TRAVIS_BUILD_NUMBER;
     sudo docker stop $CONTAINER;
     sudo docker rm $CONTAINER;
     sudo docker run --name $CONTAINER -d -p 8091:8085 $DOCKER_USERNAME/$POLITICAABERTA:1.2.$TRAVIS_BUILD_NUMBER;
     "
